import React from "react";
import "../landing_page_styles/Agenda.css";

function Agenda() {
  const agendaItems = [
    {
      name: "Natan Vidra",
      role: "Founder / CEO",
      topic: "Introduction to Anote",
      linkedinUrl: "https://www.linkedin.com/in/natanvidra/",
      talkUrl: "https://github.com/nv78/OpenAnote/tree/main/materials/marketing/AIDay/Natan-compressed.pdf",
      videoUrl: "https://www.youtube.com/watch?v=IM0ika7SOJE"
    },
    {
      name: "Liang Zhang",
      role: "Machine Learning Engineer",
      topic: "Benchmarking Text Classification Models",
      linkedinUrl: "https://www.linkedin.com/in/liang-zhang1/",
      talkUrl: "https://github.com/nv78/OpenAnote/tree/main/materials/marketing/AIDay/Liang_compressed.pdf",
      videoUrl: "https://www.youtube.com/watch?v=-jY-1tLGL_Y"
    },
    {
      name: "Katherine Jijo",
      role: "Machine Learning Engineer",
      topic: "Benchmarking Question and Answering Models",
      linkedinUrl: "https://www.linkedin.com/in/katherine-jijo-a1b231242/",
      talkUrl: "https://github.com/nv78/OpenAnote/tree/main/materials/marketing/AIDay/Katherine-compressed.pdf",
      videoUrl: "https://www.youtube.com/watch?v=sppn68PirPQ"
    },
    {
      name: "Spurthi Setty",
      role: "Machine Learning Engineer",
      topic: "Fine Tuning of Large Language Models",
      linkedinUrl: "https://www.linkedin.com/in/spurthi-setty/",
      talkUrl: "https://github.com/nv78/OpenAnote/tree/main/materials/marketing/AIDay/Spurthi_compressed.pdf",
      videoUrl: "https://www.youtube.com/watch?v=mMmaTMuRZmo"
    },
    {
      name: "Sakshi Pandey",
      role: "Product Manager",
      topic: "Build Your Own Private Financial Chatbot",
      linkedinUrl: "https://www.linkedin.com/in/sakshipandey0907/",
      talkUrl: "https://github.com/nv78/OpenAnote/tree/main/materials/marketing/AIDay/Sakshi_compressed.pdf",
      videoUrl: "https://www.youtube.com/watch?v=SB-Z1v8Emx4"
    },
    {
      name: "Eden Chung",
      role: "Machine Learning Engineer",
      topic: "PrivateGPT Chatbot Product Demo",
      linkedinUrl: "https://www.linkedin.com/in/eden-chung/",
      talkUrl: "https://github.com/nv78/OpenAnote/tree/main/materials/marketing/AIDay/Eden-compressed.pdf",
      videoUrl: "https://www.youtube.com/watch?v=XSsFmef9LJA"
    },
    // {
    //   name: "Fatima Javid",
    //   role: "Machine Learning Engineer",
    //   topic: "PrivateGPT Workflows Demo",
    //   linkedinUrl: "https://www.linkedin.com/in/fatima-javid-2223061ba/",
    //   talkUrl: "https://github.com/nv78/OpenAnote/tree/main/materials/marketing/AIDay/Fatima_compressed.pdf",
    // },
    // {
    //   name: "Christy Lin",
    //   role: "Product Manager",
    //   topic: "Upreach - An Autonomous AI Sales Agent",
    //   linkedinUrl: "https://www.linkedin.com/in/christy-lin-/",
    //   talkUrl: "https://github.com/nv78/OpenAnote/tree/main/materials/marketing/AIDay/Christy_compressed.pdf",
    //   videoUrl: "https://www.youtube.com/watch?v=d0ZkHkRLbpU"
    // },
    // {date: '2/12/2025',
    //   time: '9:00 AM EST to 10:00 AM EST',
    //   name: 'Eden Chung',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Student',
    //   company: 'Columbia University',
    //   topic: 'Columbia Devfest',
    //   description: 'Columbia Devfest Agent Presentations',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '10:00 AM EST to 10:15 AM EST',
    //   name: 'Anelya Altiyeva',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Student',
    //   company: 'Academy of Arts',
    //   topic: 'AI Agent based marketing',
    //   description: 'AI-powered marketing platform integrating blockchain to create personalized ads.',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '10:15 AM EST to 10:30 AM EST',
    //   name: 'Reyhan Merekar',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'AI Consultant',
    //   company: 'Accenture',
    //   topic: 'Newsletter AI Agent',
    //   description: 'AI Agent to find generate and topics for newsletters',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '10:30 PM EST to 10:45 PM EST',
    //   name: 'Ashwin Dhanasamy',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Graduate Student',
    //   company: 'Stevens',
    //   topic: 'Agent Optimization',
    //   description: 'Agent Optimization Demo',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '10:30 PM EST to 10:45 PM EST',
    //   name: 'Rishab Jain',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Graduate Student',
    //   company: 'Cornell Tech',
    //   topic: 'Agent Fine Tuning',
    //   description: 'Agent Optimization Demo',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '10:45 AM EST to 11:00 AM EST',
    //   name: 'Thomas Donohue, Manish Thota',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Founder',
    //   company: 'AutoABM',
    //   topic: 'AI-Powered Marketing',
    //   description: 'AI-driven ABM system capable of orchestrating end-to-end B2B marketing campaigns.',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '11:00 AM EST to 11:15 AM EST',
    //   name: 'Aisha Ahmad',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Student',
    //   company: 'Hofstra',
    //   topic: 'AI Coding Agent Writeup',
    //   description: 'https://docs.privatechatbot.ai/11_autonomous_ai_coding_agent.html',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '11:15 AM EST to 11:30 AM EST',
    //   name: 'Sanya Mahajan',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Student',
    //   company: 'Cornell',
    //   topic: 'AI RFP Agent Writeup',
    //   description: 'https://docs.privatechatbot.ai/11_autonomous_query_agent.html',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '11:30 AM EST to 11:45 AM EST',
    //   name: 'Amelia Steeger',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Consultant',
    //   company: 'EY',
    //   topic: 'Nutrition Recipe Agent',
    //   description: 'Nutrition Recipe Agent',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '11:45 AM EST to 12 PM EST',
    //   name: 'Nikita Mistri',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Software Developer',
    //   company: 'NYU',
    //   topic: 'Upreach',
    //   description: 'Upreach Agent',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '11:45 AM EST to 12 PM EST',
    //   name: 'Rajat Raghuwanshi',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Frontend Engineer',
    //   company: 'DynamoFL',
    //   topic: 'Upreach',
    //   description: 'Upreach Agent',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '11:45 AM EST to 12 PM EST',
    //   name: 'Christy Lin',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Product Designer',
    //   company: 'Mastercard',
    //   topic: 'Upreach',
    //   description: 'Upreach Agent',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '12 PM EST to 12:15 PM EST',
    //   name: 'Edmond Vea',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Founder',
    //   company: 'Vea Systems',
    //   topic: 'Medical Forms AI agent',
    //   description: 'Medical Forms AI agent presentation + demo',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '12 PM EST to 12:15 PM EST',
    //   name: 'Niyonika Chabra',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Grad Student',
    //   company: 'Cornell Tech',
    //   topic: 'Medical Forms AI agent',
    //   description: 'Medical Forms AI agent presentation + demo',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '12:15 PM EST to 12:30 PM EST',
    //   name: 'Mikhail Itenberg',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Director of IT',
    //   company: 'Camino Partners',
    //   topic: 'AI Agents for Job Applications',
    //   description: 'AI agents for job applications presentation + demo',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '12:15 PM EST to 12:30 PM EST',
    //   name: 'Sriya Challa',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Product Manager',
    //   company: 'Anote',
    //   topic: 'AI Agents for Job Applications',
    //   description: 'AI agents for job applications presentation + demo',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '12:15 PM EST to 12:30 PM EST',
    //   name: 'Alisha Shah',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Product Manager',
    //   company: 'Anote',
    //   topic: 'AI Agents for Job Applications',
    //   description: 'AI agents for job applications presentation + demo',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '12:30 PM EST to 12:45 PM EST',
    //   name: 'Sam Savage',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Founder',
    //   company: 'RoboApply',
    //   topic: 'AI Job Applications',
    //   description: 'Secret Agents Project',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '12:45 PM EST to 1:00 PM EST',
    //   name: 'Deepa Paikar',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'ML Engineer',
    //   company: 'Yeshiva University',
    //   topic: 'AI-Agent Evals',
    //   description: 'Leveraging AI Agents to Evaluate AI Agents',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '1:00 PM EST to 1:15 PM EST',
    //   name: 'Jasper Levy',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Graduate Student',
    //   company: 'Cornell Tech',
    //   topic: 'Agent Optimization',
    //   description: 'DSPY and Model Optimization / "Fine Tuning" for Agents / Evals',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '1:15 PM EST to 1:30 PM EST',
    //   name: 'Amber Zhan',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'ML Engineer',
    //   company: 'Anote',
    //   topic: 'Long Context Windows',
    //   description: 'Measuring how context window length can improve the performance of RAG',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '1:30 PM EST to 1:45 PM EST',
    //   name: 'Ben Burtenshaw',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'ML Engineer',
    //   company: 'Hugging Face',
    //   topic: 'Smol Agents',
    //   description: 'AI Agent Course',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '1:45 PM EST to 2:00 PM EST',
    //   name: 'Vanessa Escande',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'AI Consultant',
    //   company: 'Big Picture',
    //   topic: 'Agents for Logistics',
    //   description: 'How to build your own agents for logistics',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '2:00 PM EST to 2:15 PM EST',
    //   name: 'Priyankshi Gupta',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Graduate Student',
    //   company: 'Cornell Tech',
    //   topic: 'Agent Monitoring',
    //   description: 'Echosys Demo',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '2:00 PM EST to 2:15 PM EST',
    //   name: 'Dev Ashar',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Graduate Student',
    //   company: 'Cornell Tech',
    //   topic: 'Agent Monitoring',
    //   description: 'Echosys Demo',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '2:15 PM EST to 3:00 PM EST',
    //   name: 'Meghana Kesanapalli',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Student',
    //   company: 'Cornell University',
    //   topic: 'Agents SDK Package',
    //   description: 'Agent SDK Overview',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '2:15 PM EST to 3:00 PM EST',
    //   name: 'Grace Zhang',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Graduate Student',
    //   company: 'Cornell Tech',
    //   topic: 'Agents SDK Package',
    //   description: 'Inputs and Outputs of Each SDK Call',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '2:15 PM EST to 3:00 PM EST',
    //   name: 'Rishav Acharya',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'AI Developer',
    //   company: 'AI Camp',
    //   topic: 'Agents SDK Package',
    //   description: 'Agent SDK Examples',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '2:15 PM EST to 3:00 PM EST',
    //   name: 'Andrew Hing',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Student',
    //   company: 'Stevens',
    //   topic: 'Agents SDK Package',
    //   description: 'Agent SDK Use Case',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '2:15 PM EST to 3:00 PM EST',
    //   name: 'Xavier Yin',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Graduate Student',
    //   company: 'Cornell Tech',
    //   topic: 'Agents SDK Package',
    //   description: 'Private Version of Agent SDK',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '3:00 PM EST to 3:15 PM EST',
    //   name: 'Jiquan Ngiam',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Founder',
    //   company: 'Lutra',
    //   topic: 'Lutra Product Demo',
    //   description: 'AI Agents with Lutra Chat',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '3:15 PM EST to 3:30 PM EST',
    //   name: 'Amrutha Gujjar',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Founder',
    //   company: 'Structured',
    //   topic: 'Preswald Data Framework',
    //   description: 'https://github.com/StructuredLabs/preswald',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '3:30 PM EST to 3:45 PM EST',
    //   name: 'Kyra Cheng',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Product + Customer Success',
    //   company: '11X',
    //   topic: '11X AI Voice Agent Mike',
    //   description: 'https://www.11x.ai/',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '4:00 PM EST to 4:15 PM EST',
    //   name: 'John Barrus',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Product Manager',
    //   company: 'Groq',
    //   topic: 'Groq AI Product',
    //   description: 'Groq Demo',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '4:15 PM EST to 4:30 PM EST',
    //   name: 'John Gilhuly',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Head of Dev Rel',
    //   company: 'Arize',
    //   topic: 'Arize Agent Evals',
    //   description: 'Arize Demo',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '4:30 PM EST to 4:45 PM EST',
    //   name: 'Red Giuliano',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Founder',
    //   company: 'Zero-True',
    //   topic: 'Zero-True Demo',
    //   description: 'Open source reactive python notebook',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: nan},
    //  {date: '2/12/2025',
    //   time: '4:30 PM EST to 4:45 PM EST',
    //   name: 'Erica Cardenas',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Product Manager',
    //   company: 'Weaviate',
    //   topic: 'Weaviate Agents',
    //   description: 'Weaviate Demo',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '4:45 PM EST to 5:00 PM EST',
    //   name: 'Pablo Vega Bahar',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Director, Machine Learning Engineering',
    //   company: 'Fitch Ratings',
    //   topic: 'Financial Agents',
    //   description: 'financial ai agents projects',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '5:00 PM EST to 5:15 PM EST',
    //   name: 'Minh Nguyen',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'AI Engineer / Researcher',
    //   company: 'Deloitte',
    //   topic: 'Multi Agent Eval',
    //   description: 'Communication between agents, with evaluation framework',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '5:15 PM EST to 5:30 PM EST',
    //   name: 'John Lucas Facile',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'AI Engineer / Researcher',
    //   company: "Moody's",
    //   topic: 'Dynamic Chunking for RAG',
    //   description: 'improving rag with dynamic chunking',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '5:30 PM EST to 5:45 PM EST',
    //   name: 'Dan Pechi',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Generative AI Product Specialist',
    //   company: 'Databricks',
    //   topic: 'Multi Agent Framework',
    //   description: 'databricks agent framework',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '6:35 PM EST - 6:55 PM EST',
    //   name: 'Natan Vidra',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Founder / CEO',
    //   company: 'Anote',
    //   topic: 'AI Day Summit Intro',
    //   description: 'Introducing AI Day Summit',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
    //  {date: '2/12/2025',
    //   time: '6:55 PM EST - 7:15 PM EST',
    //   name: 'Spurthi Setty',
    //   linkedinUrl: 'LinkedIn',
    //   role: 'Founding ML Engineer',
    //   company: 'Anote',
    //   topic: 'AI Day Summit Agents',
    //   description: 'Agents Launch',
    //   speakerBio: nan,
    //   talkUrl: nan,
    //   videoUrl: 'Y, share URL'},
  ];

  return (
    <div className="w-screen bg-gray-900 mb-20">
      <div className="pt-10">
        <div className="text-white text-center justify-center">
          {/* <div className="text-2xl sm:text-3xl lg:text-4xl mb-5 md:mb-10 text-center font-medium lg:font-bold">
            Speakers and Agenda
          </div> */}
          <div className="text-2xl sm:text-3xl lg:text-4xl mb-5 md:mb-10 text-center font-medium lg:font-bold">
            AI Day Summit - Talks from Anote
          </div>
        </div>
        <div className="agenda-container md:mx-20">
          <table className="agenda-table ">
            <thead>
              <tr>
                <th>Name</th>
                <th>Role</th>
                <th>Talk Topic</th>
                {/* <th>Link to Slides</th>
                <th>Link to Presentation</th> */}
              </tr>
            </thead>
            <tbody>
              {agendaItems.map((item, index) => (
                <tr key={index}>
                  <td>
                    <a
                      href={item.linkedinUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      {item.name}
                    </a>
                  </td>
                  <td>{item.role}</td>
                  <td>{item.topic}</td>
                  {/* <td>
                    <a
                      href={item.talkUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      View Slides
                    </a>
                  </td>
                  <td>
                    <a
                      href={item.videoUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      Watch Presentation
                    </a>
                  </td> */}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="flex flex-col sm:flex-row justify-center">
        <button
          className="btn-yellow mb-4 sm:mb-0 sm:mr-4 w-full sm:w-auto flex justify-center items-center"
          onClick={() => {
            window.open(
              "https://www.youtube.com/watch?v=ftx72fY5s2I",
              "_blank"
            );
          }}
        >
          Watch Full Recording
        </button>
        <a
          className="btn-black w-full sm:w-auto flex justify-center items-center"
          href={"mailto:" + "nvidra@anote.ai"}
        >
          Contact Team
        </a>
      </div>
      </div>
    </div>
  );
}

export default Agenda;
