import AIDayVideo from "../AIDayVideo";
import "../../landing_page_styles/Agenda.css";

function MindstoneAugustAfter() {
    var agendaItems = [
        {
          date: "8/15, 6:35 PM EST - 6:55 PM EST",
          name: "Didier Lopes",
          role: "Founder / CEO",
          company: "OpenBB",
          topic: "Integrating an Open-Source AI Financial Analyst to a Financial Terminal",
          theme: "OpenBB Platform",
          linkedinUrl: "https://www.linkedin.com/in/didier-lopes/",
          talkUrl: "https://drive.google.com/file/d/1NsB_p2Dj-im_KqPCJqSPL915LD7-FlJ4/view?usp=sharing",
          videoUrl: "https://www.youtube.com/watch?v=Vp-CIbLf3Ng",
          videoUrlEmbed: "https://www.youtube.com/embed/Vp-CIbLf3Ng",
          description: "In this talk, Didier Lopes, founder and CEO of OpenBB, discusses how the OpenBB Platform standardizes and aggregates access to financial data. He explains how the team has open-sourced an AI financial analyst that leverages the OpenBB platform and datasets from dozens of different data vendors. Didier also explores the concept of enabling users to bring their own custom agents to financial terminals and how the OpenBB Terminal Pro facilitates this."
      },
      {
          date: "8/15, 6:55 PM EST - 7:15 PM EST",
          name: "Ben Reilly",
          role: "Founding Engineer",
          company: "Athena Intelligence",
          topic: "How to be more productive using AI",
          theme: "AI Innovations",
          linkedinUrl: "https://www.linkedin.com/in/patrickbenreilly/",
          talkUrl: "https://drive.google.com/file/d/1NsB_p2Dj-im_KqPCJqSPL915LD7-FlJ4/view?usp=sharing",
          videoUrl: "https://www.youtube.com/watch?v=VNzrkQ_vEIk",
          videoUrlEmbed: "https://www.youtube.com/embed/VNzrkQ_vEIk",
          description: "This session covers Athena Intelligence, an AI-driven platform designed to enhance decision-making by integrating sophisticated AI with systems that users can easily understand. The platform emphasizes creating solutions that are not only powerful but also intuitive, ensuring that even complex AI technologies remain accessible and effective for a diverse range of users. A key focus for Athena is on observability, which is crucial for making AI truly useful. By providing transparency and traceability in AI processes, Athena enables users to better understand and trust the outputs generated by the AI. While the AI models themselves are highly advanced, Athena believes that the real opportunity for improvement lies in refining the processes that support these models, aiming to emulate human decision-making more closely. This focus on process optimization ensures that AI can seamlessly integrate into real-world workflows, enhancing overall efficiency and effectiveness. A quick demonstration of Athena showcases these principles in action, highlighting how the platform enhances both AI observability and user understanding in practical applications."
      },
      {
          date: "8/15, 7:15 PM EST - 7:35 PM EST",
          name: "Natan Vidra",
          company: "Anote",
          role: "Founder / CEO",
          topic: "Human-Centered AI: Dynamic Systems for Optimal Model Performance",
          theme: "Human-Centered AI",
          linkedinUrl: "https://www.linkedin.com/in/natanvidra/",
          talkUrl: "https://drive.google.com/file/d/1NsB_p2Dj-im_KqPCJqSPL915LD7-FlJ4/view?usp=sharing",
          videoUrl: "https://www.youtube.com/watch?v=jk4hSnoOofA",
          videoUrlEmbed: "https://www.youtube.com/embed/jk4hSnoOofA",
          description: "Human-centered AI represents a new frontier in artificial intelligence, emphasizing dynamic, active-learning systems that adapt to the specific needs and data of end-users. This innovative approach integrates four key components—data labeling, training or fine-tuning large language models, prediction on test datasets, and evaluation—to ensure optimal model performance. By reducing hallucinations, offering customization, enhancing accuracy through active learning, and enabling the comparison and combination of multiple models, human-centered AI is poised to revolutionize applications in chatbots, spreadsheets, developer kits, and beyond. This technology provides a reliable, responsive, and user-centric AI experience, making it a powerful tool for a wide range of complex tasks."
      }
    ];


  return (
    <div className="w-screen bg-gray-900 mb-20">
      <div className="pt-10">
      <div className="text-white justify-center flex flex-col text-center pt-24">
          <div className="text-4xl sm:text-6xl  mt-8 mb-4 text-center font-medium lg:font-bold">
            August AI Meetup
          </div>
          <div className="text-xl sm:text-2xl lg:text-4xl mb-4 font-medium lg:font-bold font-['Helvetica_Neue']">
           Anote / Mindstone AI Event
        </div>
        <div className="flex flex-col mx-auto md:flex-row justify-center text-center mt-4">
<button
              className="btn-yellow mb-4 sm:mb-0 sm:mr-4 w-full sm:w-auto flex justify-center items-center inline-flex bg-yellow-500 text-gray-900 border-2 border-yellow-500 py-2 px-6 focus:outline-none hover:bg-yellow-300 rounded text-sm md:text-lg font-bold"
              onClick={() => {
                window.location.assign("https://community.mindstone.com/events/ny_ai_august_24_meetup");
              }}
            >
              Learn More
            </button>
            <a
              href={"mailto:nvidra@anote.ai"}
              className="btn-black w-full sm:w-auto flex justify-center items-center"
            >
              Contact Speakers
            </a>
            </div>
        </div>
        <div className="agenda-container md:mx-20">
          <table className="agenda-table ">
            <thead>
              <tr>
                <th>Name</th>
                <th>Company</th>
                <th>Role</th>
                {/* <th>Theme</th> */}
                <th>Talk Topic</th>
                {/* <th className="desktop-only">Link to Slides</th> */}
                <th className="desktop-only">Link to Presentation</th>
              </tr>
            </thead>
            <tbody>
              {agendaItems.map((item, index) => (
                <tr key={index}>
                  <td>
                    <a
                      href={item.linkedinUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      {item.name}
                    </a>
                  </td>
                  {/* <td>{item.date}</td> */}
                  <td>{item.company}</td>
                  <td>{item.role}</td>
                  {/* <td>{item.theme}</td> */}
                  <td>{item.topic}</td>
                  {/* <td className="desktop-only">
                    <a
                      href={item.talkUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      View Slides
                    </a>
                  </td> */}
                  <td className="desktop-only">
                    <a
                      href={item.videoUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      Watch Presentation
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
      </div>
    </div>
    <div className="LP-FAQs pt-10 bg-gray-900">
    <div className="FAQ">
      <div className={"LP-Sample-Projects bg-gray-900"}>
        {agendaItems.map((item, index) => (
          <div key={index}>
            <h1 className="TutorialHeader mb-3 bg-gray-900">
              {item.topic}
            </h1>
            <div className="LP-Contact">
              <AIDayVideo
                title={item.name}
                description={item.description}
                capability={item.role}
                sector={item.topic} // You can customize this if needed
                type={item.role}
                videoUrl={item.videoUrlEmbed}
                slideUrl={item.linkedinUrl}
              />
              <hr className="Green-Line-New" style={{ width: "100%" }} />
            </div>
          </div>
        ))}
      </div>
    </div>
  </div>
  </div>
  )
}

export default MindstoneAugustAfter;